services:
  - type: web
    name: burgercy-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: PERSISTENT_STORAGE_DIR
        value: /data
    disk:
      name: burger-data
      mountPath: /data
      sizeGB: 1
